variable subscription_id {}
variable client_id {}
variable client_secret {}
variable tenant_id {}
variable vm_name {}
variable vm_size {}
variable resource_group {}
variable location {}
variable username {}
variable ssh_key {}
